on:
  workflow_call: {}
  workflow_dispatch: {}

name: Get Current Pages Artifact

jobs:
  print-files:
    runs-on: ubuntu-latest
    steps:
      - name: Download Pages Artifact
        uses: actions/download-artifact@v4
        with:
          name: github-pages
          path: ./current-build

      - name: Extract Files
        run: tar -xvf ./current-build/artifact.tar -C ./current-build

      - name: Output All Files to Console
        run: |
          echo "=== DIRECTORY STRUCTURE ==="
          ls -R ./current-build
          
          echo "=== FILE CONTENTS ==="
          find ./current-build -type f ! -name "*.tar" -exec echo -e "\n--- File: {} ---" \; -exec cat {} \;