on:
  workflow_call: {}
  workflow_dispatch: {}

name: Get Current Pages Artifact

jobs:
  dump-logs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Output Everything to Console
        run: |
          echo "========================================="
          echo "   COMPLETE RECURSIVE DIRECTORY TREE     "
          echo "========================================="
          find . -maxdepth 5 -not -path '*/.*'         
